### PR TITLE
Implement rich messages

### PR DESCRIPTION
**Pull request by SkUrRiEr**
This is preliminary work towards being able to specify messages as

`Awesome, <item> has <score> point<plural> now!`
or
`*<score>* Ha ha ha! (lightning cracks)`

The next step is to convert the message store.

### CODE REVIEW

**Comment by tdmalone** [comment]
Looks good! I've retargeted this PR for the `dev` branch as there has been a bit of work on restructuring (mainly to make it easier to test) that hasn't been merged into `master` yet. dev also has a .travis.yml too, so Travis CI should automatically lint and test the code... well, as much as the tests that have been written so far anyway ;)

If you want to test it locally against Slack, there's also more instructions now in the dev README on running locally.

**Comment by tdmalone** [comment]
I've fixed the conflicts between this PR and `dev`, and pushed them to the brach `rich-messages`.

The new diff can be seen here: https://github.com/tdmalone/working-plusplus/compare/dev...rich-messages

I don't think I can push to this PR; @SkUrRiEr if you'd like to select 'allow edits from maintainers' on the right then I can do that, otherwise feel free to bring the changes into your branch yourself.

Now that `dev` is in there, Travis is building - the current result can be seen [here](https://travis-ci.com/tdmalone/working-plusplus/builds/81333253). We'll just need to adjust the tests on the operations to utilise the new constants, and also run a `yarn fix` to resolve most of the linting issues, there should then only be a few to resolve manually.

I don't think I put this in the eslintrc - I probably should - but it would be good if you could also change the `var`s to `let`s if they are gonna change, or `const` if they're not gonna change (see [this article](https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75) for a quick backgrounder).

**Comment by tdmalone** [comment]
Oh - one other thing - I went for `operations` and `operation` when merging in https://github.com/tdmalone/working-plusplus/compare/dev...rich-messages, rather than `operation` and `op`. I feel it's a bit clearer.

**Comment by SkUrRiEr** [comment]
Ok, I've added Yarn as a dev dependency as I don't have it installed globally and it's required to run tests.

I've also fixed a couple of bugs and removed some broken tests.

Hopefully it's mergeable now!

**Comment by tdmalone** [comment]
> Ok, I've added Yarn as a dev dependency as I don't have it installed globally and it's required to run tests.

Oh, good point. It's not actually required but I should document that. You can alternatively just use `npm run test`, the only thing with npm is you won't get the _exact_ same dependencies but that's not likely to be a massive issue.

Tests are passing but linting is failing - I can fix that up after merge.

Have you tested against a real Slack?

**Comment by tdmalone** [comment]
Ok no worries =] I will merge now and test locally before I merge into master!

(Automated tests aren't anywhere near good enough yet, but hopefully not too far off.. just need to finish messing around with Express and then mock Slack)

**Pull request merged**
